CREATE TABLE Subreddit (
    subreddit_id VARCHAR2(50) PRIMARY KEY,  
    name VARCHAR2(100) NOT NULL,           
    description CLOB,                       
    subscriber_count NUMBER,                
    active_users NUMBER,                    
    created_at DATE                         
);

CREATE TABLE Post (
    post_id VARCHAR2(50) PRIMARY KEY,       
    title CLOB NOT NULL,                    
    content CLOB,                           
    author VARCHAR2(50),                    
    score NUMBER,                           
    flair VARCHAR2(100),                    
    num_comments NUMBER,                    
    media_url CLOB,                         
    subreddit_id VARCHAR2(50) NOT NULL,     
    created_at DATE,    
    label VARCHAR2(10),                    
    CONSTRAINT fk_post_subreddit FOREIGN KEY (subreddit_id)
        REFERENCES Subreddit(subreddit_id)
);


CREATE TABLE Comments (
    comment_id VARCHAR2(50) PRIMARY KEY,   
    content CLOB NOT NULL,                
    author VARCHAR2(50),                    
    score NUMBER,                           
    post_id VARCHAR2(50) NOT NULL,          
    parent_comment_id VARCHAR2(50),         
    created_at DATE,    
    label VARCHAR2(10),                    
    CONSTRAINT fk_comment_post FOREIGN KEY (post_id)
        REFERENCES Post(post_id),
    CONSTRAINT fk_comment_parent FOREIGN KEY (parent_comment_id)
        REFERENCES Comments(comment_id)
);

CREATE TABLE SubredditSentiments (
    sentiment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    subreddit_id VARCHAR2(50) NOT NULL,                                
    sentiment_analysis CLOB NOT NULL,                                 
    created_at DATE DEFAULT SYSDATE,                                  
    CONSTRAINT fk_sentiment_subreddit FOREIGN KEY (subreddit_id)
        REFERENCES Subreddit(subreddit_id)
);


SELECT * FROM SUBREDDIT;
SELECT * FROM POST;
SELECT * FROM COMMENTS;
SELECT * FROM SubredditSentiments;

DROP TABLE SUBREDDIT;
DROP TABLE COMMENTS;
drop TABLE POST;
DROP TABLE SubredditSentiments;


